/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Controller;
import Model.Buku;
import Model.KategoriBuku;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Tables.TableBuku;
import javax.swing.table.TableModel;

/**
 *
 * @author bangz
 */
public class BukuView extends javax.swing.JFrame {
    Controller C = new Controller();
    KategoriBuku KB;
    Buku B;
    String action = null;
    List<KategoriBuku> listKategori;

//    private List<Buku> list;

    /**
     * Creates new form Buku
     */
    public BukuView() {
        initComponents();
        setComponents(false);
        showBuku();
        setKategoriComboBox();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
     public void setComponents (boolean value) {
        
        InputIdBuku.setEnabled(value);
        InputJudul.setEnabled(value);
        KategoriComboBox.setEnabled(value);
        InputPenulis.setEnabled(value);
        InputPenerbit.setEnabled(value);
        InputTahunTerbit.setEnabled(value);
        InputStok.setEnabled(value);
        InputHarga.setEnabled(value);
       
    }
    
    public void clearText(){
        InputIdBuku.setText("");
        InputJudul.setText("");
        InputPenerbit.setText("");
        InputPenulis.setText("");
        InputTahunTerbit.setText("");
        InputStok.setText("");
        InputHarga.setText("");
        KategoriComboBox.setEnabled(false);
    }
     public void setEditDeleteBtn(boolean value){
        Btn_UpdateBuku.setEnabled(value);
        Btn_DeleteBuku.setEnabled(value);
    }
    
     public void setKategoriComboBox() {
        listKategori = C.showListKategoriBukuComboBox();
        for (int i = 0; i < listKategori.size(); i++) {
            KategoriComboBox.addItem(listKategori.get(i));
        }
    }
     
     public void showBuku(){
        Tbl_Buku.setModel(C.showDataBuku(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        InputJudul = new javax.swing.JTextField();
        InputTahunTerbit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        InputPenulis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputPenerbit = new javax.swing.JTextField();
        InputIdBuku = new javax.swing.JTextField();
        KategoriComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnAddKategori = new javax.swing.JButton();
        InputHarga = new javax.swing.JTextField();
        BtnAddBuku = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        Btn_save = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        BtnSearchBuku = new javax.swing.JButton();
        InputSearch = new javax.swing.JTextField();
        Btn_UpdateBuku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Buku = new javax.swing.JTable();
        Btn_DeleteBuku = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 237, 240));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("Data Buku");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/twemoji_books_1.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/tokobukujamal_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(572, 572, 572)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(221, 237, 240));

        InputJudul.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        InputTahunTerbit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Stok");

        InputPenulis.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Judul");

        InputPenerbit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        InputIdBuku.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        InputIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputIdBukuActionPerformed(evt);
            }
        });

        KategoriComboBox.setEditable(true);
        KategoriComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        KategoriComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Kategori");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Tahun Terbit");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("ID Buku");

        InputStok.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Penerbit");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Penulis");

        BtnAddKategori.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnAddKategori.setText("Add Kategori");
        BtnAddKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddKategoriActionPerformed(evt);
            }
        });

        InputHarga.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        BtnAddBuku.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnAddBuku.setText("Add");
        BtnAddBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddBukuActionPerformed(evt);
            }
        });

        BtnReset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnReset.setText("Reset");

        Btn_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Btn_save.setText("Save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputIdBuku)
                                .addComponent(InputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BtnAddKategori)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(InputPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(BtnAddBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(InputIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(KategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(BtnAddKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(InputPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(InputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(InputTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(InputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAddBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel4.setBackground(new java.awt.Color(221, 237, 240));

        BtnSearchBuku.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnSearchBuku.setText("Search");
        BtnSearchBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchBukuActionPerformed(evt);
            }
        });

        InputSearch.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        Btn_UpdateBuku.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Btn_UpdateBuku.setText("Update");
        Btn_UpdateBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateBukuActionPerformed(evt);
            }
        });

        Tbl_Buku.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Tbl_Buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Kategori", "Penulis", "Penerbit", "Tahun Terbit", "Stok", "Harga"
            }
        ));
        Tbl_Buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_BukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Buku);

        Btn_DeleteBuku.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Btn_DeleteBuku.setText("Delete");
        Btn_DeleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteBukuActionPerformed(evt);
            }
        });

        BtnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ic_round-home.png"))); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Btn_UpdateBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_DeleteBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(64, 64, 64))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSearchBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_UpdateBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DeleteBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputIdBukuActionPerformed

    private void BtnAddBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddBukuActionPerformed
        // TODO add your handling code here:
        setComponents(true);
          action="Tambah";
          
    }//GEN-LAST:event_BtnAddBukuActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HomeView().setVisible(true);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnAddKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddKategoriActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TambahKategoriView().setVisible(true);
    }//GEN-LAST:event_BtnAddKategoriActionPerformed

    private void Btn_DeleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteBukuActionPerformed
        // TODO add your handling code here:
        action ="delete";
        
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?","Konfirmasi", JOptionPane.YES_NO_OPTION);
        String idbk= InputIdBuku.getText();
        switch(getAnswer){
            case 0:
            try{
                C.deleteBuku(idbk);
                clearText();
                
                setComponents(false);
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            }catch (Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;

            case 1:
                JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
            break;
        }
        showBuku();
    }//GEN-LAST:event_Btn_DeleteBukuActionPerformed

    private void Btn_UpdateBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateBukuActionPerformed
        // TODO add your handling code here:
        action="update";
        setComponents(true);
        InputIdBuku.setEnabled(false);
        
    }//GEN-LAST:event_Btn_UpdateBukuActionPerformed

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        // TODO add your handling code here:
//        try{

           int namaKategori = KategoriComboBox.getSelectedIndex();
            
            KategoriBuku selectedKategori =  listKategori.get(namaKategori);
            Buku b = new Buku(InputIdBuku.getText(),InputJudul.getText(), InputPenulis.getText(), InputPenerbit.getText(), Integer.parseInt(InputTahunTerbit.getText()), Integer.parseInt(InputStok.getText()), Integer.parseInt(InputHarga.getText()),selectedKategori);
            System.out.println(b.getKategori_buku().getId_kategori());
//            Member m =new Member();        
//            C.setMember(InputIDMember.getText(), InputNamaMember.getText(), jenisKelamin, InputNoHanphone.getText(), InputAlamat.getText());
//String id_buku, String judul_buku, String penerbit_buku, String penulis_buku, int tahun_terbit, int stok, float harga_buku, KategoriBuku kategori_buku
            if(action.equals("Tambah")){

                C.insertBuku(b);
                JOptionPane.showMessageDialog(null, "Data berhasil ditambah!");
            }else{
                System.out.println(b.showBuku());
               C.updateBuku(b);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            }
  
            clearText();
           
            setComponents(false);
            setEditDeleteBtn(false);
            
            showBuku();
//     
//        }catch(Exception e){
//          JOptionPane.showMessageDialog(null, "Harap isi data dengan benar!");
//        }
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void Tbl_BukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_BukuMouseClicked
        // TODO add your handling code here:
        int indexMember= -1;
        setEditDeleteBtn(true); //u can edit n delete when click particular row
        setComponents(false);
        
        int clickedRow = Tbl_Buku.getSelectedRow();
        TableModel tableModel = Tbl_Buku.getModel();
        
        InputIdBuku.setText(tableModel.getValueAt(clickedRow,0).toString());
        InputJudul.setText(tableModel.getValueAt(clickedRow, 1).toString());
        KategoriComboBox.setSelectedItem(tableModel.getValueAt(clickedRow, 2).toString()); //udah bener belum
        InputPenulis.setText(tableModel.getValueAt(clickedRow, 3).toString());
        InputPenerbit.setText(tableModel.getValueAt(clickedRow, 4).toString());
        InputTahunTerbit.setText(tableModel.getValueAt(clickedRow, 5).toString());
        InputStok.setText(tableModel.getValueAt(clickedRow, 6).toString());
        InputHarga.setText(tableModel.getValueAt(clickedRow, 7).toString());
        
        // tanya kenapa yang muncul gasemua 
    }//GEN-LAST:event_Tbl_BukuMouseClicked

    private void BtnSearchBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchBukuActionPerformed
        // TODO add your handling code here:
        setEditDeleteBtn(false);
        setComponents(false);
        
        try{
            TableBuku member = C.showDataBuku(InputSearch.getText());
            if(member.getRowCount()== 0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, "Data member tidak ditemukan");
            } else {
                Tbl_Buku.setModel(member);
            }
        }catch(Exception e){
            System.out.println("error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnSearchBukuActionPerformed

    private void KategoriComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddBuku;
    private javax.swing.JButton BtnAddKategori;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSearchBuku;
    private javax.swing.JButton Btn_DeleteBuku;
    private javax.swing.JButton Btn_UpdateBuku;
    private javax.swing.JButton Btn_save;
    private javax.swing.JTextField InputHarga;
    private javax.swing.JTextField InputIdBuku;
    private javax.swing.JTextField InputJudul;
    private javax.swing.JTextField InputPenerbit;
    private javax.swing.JTextField InputPenulis;
    private javax.swing.JTextField InputSearch;
    private javax.swing.JTextField InputStok;
    private javax.swing.JTextField InputTahunTerbit;
    private javax.swing.JComboBox<KategoriBuku> KategoriComboBox;
    private javax.swing.JTable Tbl_Buku;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
