/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Controller;
import javax.swing.JOptionPane;
import Model.KategoriBuku;
import java.util.List;
import Exception.InputanKosongException;
import javax.swing.table.DefaultTableModel;
import Tables.TableKategoriBuku;
import javax.swing.table.TableModel;

/**
 *
 * @author bangz
 */
public class TambahKategoriView extends javax.swing.JFrame {
    Controller C = new Controller();
    KategoriBuku KB;
    String action = null;
    private List<KategoriBuku> list;
    

    /**
     * Creates new form TambahKategori
     */
    public TambahKategoriView() {
        initComponents();
        showTableKategori();
        setComponents(false);
        clearText();
    }
     public void setComponents (boolean value) {
        
        InputIDKategori.setEnabled(value);
        InputKategori.setEnabled(value);
//        InputSearch.setEnabled(value);
        Btn_SaveKategori.setEnabled(value);
//        Btn_Back.setEnabled(value);
        Btn_Reset.setEnabled(value);
       
    }
    
    public void clearText(){
        InputIDKategori.setText("");
        InputKategori.setText("");
    }
    
//    public void showTableKategori(){
//    Tbl_Kategori.setModel((TableModel) C.showKategoriBuku());
//    }
    
    public void showTableKategori(){
    Tbl_Kategori.setModel(C.showDataKategoriBuku(""));
    }
    
//    public void showTable(){
////        Tbl_Kategori = new DefaultTableModel(new String[]{"ID Kategori", "Kategori"},0);
////        C.showListKategoriBuku();
////        Tbl_Kategori.addRow(new Object[]  );
//        try{
//            
//            KategoriBuku KB = new KategoriBuku();
//            C.showKategoriBuku();
//            
//            DefaultTableModel model = new DefaultTableModel();
//            model.addColumn("ID Kategori");
//            model.addColumn("Kategori");
//            
//            model.getDataVector().removeAllElements();
//            model.fireTableDataChanged();
//            model.setRowCount(0);
//            
//  
//            
//        }catch(Exception e){
//        
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InputIDKategori = new javax.swing.JTextField();
        InputKategori = new javax.swing.JTextField();
        Btn_AddKategori = new javax.swing.JButton();
        Btn_Reset = new javax.swing.JButton();
        Btn_Back = new javax.swing.JButton();
        Btn_SaveKategori = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Kategori = new javax.swing.JTable();
        InputSearch = new javax.swing.JTextField();
        Btn_Search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 237, 240));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("ID Kategori");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Kategori");

        InputIDKategori.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        InputKategori.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        Btn_AddKategori.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Btn_AddKategori.setText("Add");
        Btn_AddKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddKategoriActionPerformed(evt);
            }
        });

        Btn_Reset.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Btn_Reset.setText("Reset");
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        Btn_Back.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Btn_Back.setText("Back");
        Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackActionPerformed(evt);
            }
        });

        Btn_SaveKategori.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Btn_SaveKategori.setText("Save");
        Btn_SaveKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SaveKategoriActionPerformed(evt);
            }
        });

        Tbl_Kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Kategori", "Kategori"
            }
        ));
        Tbl_Kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_KategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Kategori);

        InputSearch.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        Btn_Search.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Btn_Search.setText("Search");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 110, 172));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/heroicons_square-3-stack-3d-solid.png"))); // NOI18N
        jLabel1.setText("Tambah Kategori");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_AddKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addComponent(Btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(78, 78, 78)
                                .addComponent(InputIDKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(109, 109, 109)
                                .addComponent(InputKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                                .addComponent(Btn_SaveKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(InputSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InputIDKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_Search)
                        .addComponent(InputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_AddKategori)
                            .addComponent(Btn_Reset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_SaveKategori)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackActionPerformed
        // TODO add your handling code here:
        BukuView B = new BukuView();
        this.dispose();
        B.setVisible(true);
        
    }//GEN-LAST:event_Btn_BackActionPerformed

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
        // TODO add your handling code here:
        clearText();
        setComponents(true);
    }//GEN-LAST:event_Btn_ResetActionPerformed

    private void Btn_AddKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddKategoriActionPerformed
        // TODO add your handling code here:
        setComponents(true);
        clearText();
        InputSearch.setText("");
        action = "Tambah";
    }//GEN-LAST:event_Btn_AddKategoriActionPerformed

    private void Btn_SaveKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SaveKategoriActionPerformed
        // TODO add your handling code here:
         try{

            KategoriBuku KB = new KategoriBuku(InputIDKategori.getText(), InputKategori.getText() );
            C.setKategoriBuku(InputIDKategori.getText(), InputKategori.getText());

            if(action.equals("Tambah")){
                C.insertKategoriBuku(KB);
                JOptionPane.showMessageDialog(null, "Data kategori buku berhasil ditambah!");
            }
            clearText();
            setComponents(false);
            
     }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Harap isi data dengan benar!");
        }
         showTableKategori();
    }//GEN-LAST:event_Btn_SaveKategoriActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        // TODO add your handling code here:
//        action = "Search";
        setComponents(false);
         try{
            TableKategoriBuku kategoriBuku = C.showDataKategoriBuku(InputSearch.getText());
            if(kategoriBuku.getRowCount()== 0){
                clearText();
                JOptionPane.showMessageDialog(null, "Data kategori buku tidak ditemukan");
            } else {
                Tbl_Kategori.setModel(kategoriBuku);
            }
        }catch(Exception e){
            System.out.println("error : " + e.getMessage());
        }
        
    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void Tbl_KategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_KategoriMouseClicked
        // TODO add your handling code here:
        int indexMember= -1;
//        setComponents(false);
        clearText();
        Btn_SaveKategori.setEnabled(true);
        Btn_Reset.setEnabled(true);
       
        int clickedRow = Tbl_Kategori.getSelectedRow();
        TableModel tableModel = Tbl_Kategori.getModel();
        
        InputIDKategori.setText(tableModel.getValueAt(clickedRow,0).toString());
        InputKategori.setText(tableModel.getValueAt(clickedRow, 1).toString());
        
    }//GEN-LAST:event_Tbl_KategoriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKategoriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKategoriView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AddKategori;
    private javax.swing.JButton Btn_Back;
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JButton Btn_SaveKategori;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JTextField InputIDKategori;
    private javax.swing.JTextField InputKategori;
    private javax.swing.JTextField InputSearch;
    private javax.swing.JTable Tbl_Kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
